pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('Run HelloWorld.js') {
      agent any
      steps {
        // Checkout the code from the GitHub repository
        git 'https://github.com/Chandinivilluri/Zero-to-Hero-Jenkins.git'

        // Run HelloWorld.js using Node.js
        dir('path/to/Zero-to-Hero-Jenkins') {
          sh 'node HelloWorld.js'
        }
      }
    }
  }
}
